apiVersion: v1

kind: Pod

metadata:

name: "mariadb-centos7"

labels:

name: "mariadb-centos7"

spec:

containers:

-

image: mysql:latest

name:  "mysql"

env:

-

name: "MYSQL_ROOT_PASSWORD"

value: "falp"

ports:

-

containerPort: 3306

name:  "mysql"

volumeMounts:

-

name: "k8s-mysql-storage"

mountPath: "/var/lib/mysql"

volumes:

- name: "k8s-mysql-storage"

emptyDir: {}
