---
- hosts: masters
#  name: Build Up Kubernetes Server
  pre_tasks:
    - shell: echo "Initializing Kubernetes Support.."
  roles:
    - { role: master, tags: ['master']}
    - { role: docker, tags: ['docker']}
    - { role: etcd, tags: ['etcd']}
    - { role: kubernetes, tags: ['kubernetes'] }
  post_tasks:
    - shell: echo "Finalizing Kubernetes Process"
