---
- hosts: masters
#  name: Build Up Kubernetes Server
  pre_tasks:
    - shell: echo "Initializing Kubernetes Support.."
  roles:
    - { role: etcd }
    - { role: kubernetes }
  post_tasks:
    - shell: echo "Finalizing Kubernetes Process"
