apiVersion: v1
kind: ReplicationController
metadata:
  name: webdon01
spec:
  replicas: 2
  selector:
    app: webdon01
  template:
    metadata:
      name: webdon01
      labels:
        app: webdon01
    spec:
      containers:
      - name: webdon01
        image: webdon01
        ports:
        - containerPort: 80
