---
- name: Make sure ntpd service is enabled
  systemd: 
     name: ntpd
     enabled: yes

- name: reload service ntpd, in all cases
  systemd:
    name: ntpd
    state: restarted

- name: Make sure etcd service is enabled
  systemd: 
     name: etcd
     enabled: yes

- name: reload service etcd, in all cases
  systemd:
    name: etcd
    state: restarted

- name: Configure a Flannel network
  shell: etcdctl mk /flannel/network/config '{"Network":"172.17.0.0/16"}'
