---
- name: Install list of Packages
  yum: name={{ item }} state=installed
  with_items:
      - kubernetes 

- name: Copy kube-dns yaml file
  copy: src=skydns-svc.yml dest=/srv
  tags:
    - cp_skydns_svc

- name: Copy kube-rc yaml file
  copy: src=skydns-rc.yml dest=/srv
  tags:
    - cp_skydns_rc

- name: Copy apache-centos7 file
  copy: src=apache-centos7.json dest=/srv
  tags:
    - cp_apache_json

- name: Copy mariadb-centos7 file
  copy: src=mariadb-centos7.yml dest=/srv
  tags:
    - cp_mariadb_json
