---
- name: Install list of Packages
  yum: name={{ item }} state=installed
  with_items:
      - kubernetes 

#- name: Copy kubernetes config file
#  copy: src=kube.conf dest=/etc/kubernets/kube.conf

