---
- name: Sync MySql Galera Service
  copy:
    src: db/mariadb-galera
    dest: /srv
  tags:
    - rsync_db_mysql-galera

- name: Building MySql Galera Service
  shell: kubectl create -f /srv/mariadb-galera/pxc-cluster-service.yaml --validate=false
  tags:
    - build_db_mariadb-galera_cluster_service

- name: Building MySql Galera Local Volume
  shell: kubectl create -f /srv/mariadb-galera/pxc-local-volumes.yaml --validate=false
  tags:
    - build_db_mariadb-galera_local_volume

- name: Building MySql Galera Service
  shell: kubectl create -f /srv/mariadb-galera/pxc-node1.yaml --validate=false
  tags:
    - build_db_mariadb-galera_replication_controllers
