---
- name: Configuration Clamav
  synchronize: 
    src=clamav
    dest=/etc/
    checksum=yes
    recursive=yes
    archive=yes

- name: restart clamav service
  service: name=clamav-freshclam state=restarted
