---
- name: Replacing Kubelet API Server Address
  replace:
    dest: /etc/kubernetes/apiserver
    regexp: 'KUBE_API_ADDRESS="--insecure-bind-address=127.0.0.1"'
    replace: 'KUBE_API_ADDRESS="--address=0.0.0.0"'
    backup: yes
  tags:
    - replace_kube_api_serv_addr

- name: Replacing Kubelet address
  replace:
    dest: /etc/kubernetes/kubelet
    regexp: 'KUBELET_ADDRESS="--address=127.0.0.1"'
    replace: 'KUBELET_ADDRESS="--address=0.0.0.0"'
  tags:
    - replace_kubelet_addr

- name: Inserting Kubelet port
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: 'KUBELET_PORT'
    state: present
    line: 'KUBELET_PORT="--port=10250"'
  tags:
    - replace_kubelet_port

- name: Inserting Kubelet name
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: 'KUBELET_HOSTNAME'
    state: present
    line: 'KUBELET_HOSTNAME="--hostname_override={{ ansible_default_ipv4.address }}"'
  tags:
    - replace_kubelet_name

- name: Replacing Kubelet api
  replace:
    dest: /etc/kubernetes/kubelet
    regexp: 'KUBELET_API_SERVER="--api-servers=http://127.0.0.1:8080"'
    replace: 'KUBELET_API_SERVER="--api-servers=http://{{ ansible_default_ipv4.address }}:8080"'
  tags:
    - replace_kubelet_addr

- name: Enabling kubernetes service
  systemd: name={{ item }} enabled=yes
  with_items:
      - kube-apiserver
      - kube-controller-manager 
      - kube-scheduler

- name: Restarting kubernetes service
  systemd: name={{ item }} state=restarted
  with_items:
      - kube-apiserver
      - kube-controller-manager 
      - kube-scheduler
  tags:
    - restart_kubernetes_service
