---
- name: Enabling kubernetes service
  systemd: name={{ item }} enabled=yes
  with_items:
      - kube-apiserver
      - kube-controller-manager 
      - kube-scheduler

- name: Restarting kubernetes service
  systemd: name={{ item }} state=restarted
  with_items:
      - kube-apiserver
      - kube-controller-manager 
      - kube-scheduler
