apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pxc-1
  labels:
    type: local
    unit: pxc-cluster
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pxc-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pxc-2
  labels:
    type: local
    unit: pxc-cluster
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pxc-2
